### ISSUE TITLE
let: Symbol’s value as variable is void: sunrise-left-window

### ISSUE THREAD

**Issue by breadncup** [sunrise-commander/sunrise-commander#114] opened 2021-04-11 20:38 UTC
Hello, there,

I'm using emacs on MacOS Big Sur and using this emacs version:

GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.4.0, Carbon Version 164 AppKit 2022.44) of 2021-04-01

Now, when I run the `M-x sunrise` I got following error and not working:

        Starting Sunrise Commander...
        let: Symbol’s value as variable is void: sunrise-left-window

**Comment by breadncup** [comment] 2021-04-11 21:15
diff --git a/sunrise.el b/sunrise.el
    index 1db67e7..c090121 100644
    --- a/sunrise.el
    +++ b/sunrise.el
    @@ -1526,7 +1526,6 @@ buffer or window."

     SIDE is one of the symbols left or right."
       `(let ((sunrise-selected-window ',side))
    -     (setq ,(sunrise-symbol side 'window) (selected-window))
          (setq ,(sunrise-symbol side 'directory)
                (sunrise--setup-pane-internal
                 ,(sunrise-symbol side 'directory)
    (END)

I think the change above causes the issue.

**Comment by thblt** [comment] 2021-04-15 14:46
I confirm the issue on Emacs 28.5 (HEAD from a few day ago) on NixOS. This is reproducible from `-Q`.

**Comment by lassik** [comment] 2021-04-16 07:41
Sorry about the delay in responding. The window handling was quite ad hoc and led to the window layout getting accidentally messed up in many practical situations (at least in my usage) so I started making somewhat disruptive changes to the code.

The new idea is to inspect the current frame's window layout on each call to a Sunrise command, figuring out what state SC is in. If any SC command is called when SC is hidden or its window layout is not as expected, it will fix things. The code isn't quite stable yet, and I seem to not have committed the latest work.

@breadncup @thblt Do you have some time to hack on SC? If so, we should talk about how to split tasks. I'll finish the window layout stuff ASAP in any case.

**Comment by lassik** [comment] 2021-04-16 07:44
E.g. in the case of the present bug, SC kept information about which window is the left one in the `sunrise-left-window` variable. But storing window info in a variable is quite brittle since the user can change the window layout at any time without telling SC. So I wrote some code to programmatically figure out whether SC is being displayed, and if so, what window is the left pane.

**Comment by thblt** [comment] 2021-04-19 12:29
I won't have time to do any serious work, but I'd be happy to help a bit if I can. The first thing that comes to mind re that specific bug is using `window-configuration-change-hook` to spy on changes on the

**Comment by thblt** [comment] 2021-04-19 12:36
The previous message was sent too early in error, and I've edited it to complete it. If you've received it in an email, it probably isn't complete.

**Comment by lassik** [comment] 2021-04-19 15:14
Thanks for commenting. From my understanding of the code, I can't think of any situation where a hook is needed; running a detection function before each SC command should be enough. I wrote such a function and it runs instantaneously; no slowdown. The function does basically those checks that you list.

**Comment by lassik** [comment] 2021-04-19 15:15
`define-sunrise-command` might be a good idea. There are probably some commands that don't need this functionality, but they are probably a small minority.

**Comment by lassik** [comment] 2021-04-19 15:16
Do you expect to have time to write some code? If not, commenting on issues and reviewing PRs is valuable as well.

**Comment by thblt** [comment] 2021-04-19 18:14
> Do you expect to have time to write some code?

I can help wrapping that function you write in a macro, if you wish :) On second thought, I think something simpler, like `sunrise-with-sunrise` that you'd wrap inside a defun would probably be better. What do you think?

> If not, commenting on issues and reviewing PRs is valuable as well.

I'll try!

As an aside, if you need contributions, why not publish Sunrise on either ELPA or Melpa? It's a really cool package that's relatively hard to discover.

**Comment by lassik** [comment] 2021-04-19 19:42
Good idea, putting `sunrise-with-sunrise` inside an ordinary defun is less surprising.

The current code is slightly messy so it's easiest if I clean it up before adding the macro. I'll try to have it pushed to master sometime in the next 24 hours.

The intention is to submit SC to MELPA as soon as we can, but there is quite a lot of unresolved issues. [Milestone 1](https://github.com/sunrise-commander/sunrise-commander/milestone/1)) tracks what needs to be resolved before we submit.

**Comment by lassik** [comment] 2021-04-25 10:37
This was fixed in the commits a couple days ago, but there are bound to be some problems lurking still.

**Closed by lassik** 2021-04-25 10:37 UTC
