### ISSUE TITLE
Pane content fails to render

### ISSUE THREAD

**Issue by rnadler** [sunrise-commander/sunrise-commander#113] opened 2021-03-22 15:38 UTC
Emacs: 27.1.91
Doom: v2.0.9
Configuration:
```(package! sunrise-commander :recipe (:host github :repo "sunrise-commander/sunrise-commander"))```
 
Panes are split, but they have no dired or button content. Error message:
```
Starting Sunrise Commander...
sunrise--dired-internal: Symbol’s value as variable is void: sunrise-left-window
```

Debugger:
```
Debugger entered--Lisp error: (void-variable sunrise-left-window)
  sunrise-select-window(left)
  sunrise--dired-internal("~/" nil nil)
  sunrise--setup-pane-internal("~/" nil)
  sunrise-setup-visible-panes()
  sunrise-setup-windows(nil nil)
  sunrise-show()
  sunrise()
  sunrise--dired-internal("~/" nil t)
  sunrise-dired("~/")
  sunrise-cd()
  funcall-interactively(sunrise-cd)
  call-interactively(sunrise-cd nil nil)
  command-execute(sunrise-cd)
```

**Comment by mocus-focus** [comment] 2021-03-27 18:49
Exactly the same thing here with:
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28
Additionally, I want to point out two warning messages produced by byte-compiling sunrise.el:
`In sunrise:
sunrise.el:1329:10:Warning: sunrise called with 3 arguments, but accepts only
    0

In sunrise-setup-windows:
sunrise.el:1418:8:Warning: function sunrise-setup-windows used to take 0-2
    arguments, now takes 0

`

**Comment by thblt** [comment] 2021-04-19 17:54
This is a duplicate of #114.

**Comment by lassik** [comment] 2021-04-19 19:38
Thanks. Closing as duplicate.

**Closed by lassik** 2021-04-19 19:38 UTC
